# Generated by Django 3.2.9 on 2021-12-08 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callofdutyapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GunStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=6)),
                ('gun_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callofdutyapi.gun')),
                ('stat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callofdutyapi.stat')),
            ],
        ),
        migrations.CreateModel(
            name='CreatedClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('base_gun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callofdutyapi.gun')),
            ],
        ),
        migrations.CreateModel(
            name='AttachmentStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.DecimalField(decimal_places=3, max_digits=4)),
                ('attachment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callofdutyapi.attachment')),
                ('stat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callofdutyapi.stat')),
            ],
        ),
        migrations.CreateModel(
            name='AttachmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('attachment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callofdutyapi.attachment')),
                ('createdclass_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callofdutyapi.createdclass')),
            ],
        ),
    ]
