# Generated by Django 3.2.9 on 2021-12-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callofdutyapi', '0002_attachment_attachmentslot_attachmentstat_createdclass_gunstat_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gunstat',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
