# Generated by Django 3.2.9 on 2021-12-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callofdutyapi', '0003_alter_gunstat_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gunstat',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
