# Generated by Django 3.2.9 on 2021-12-10 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callofdutyapi', '0004_alter_gunstat_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='attachmenttype_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='callofdutyapi.attachmenttype'),
            preserve_default=False,
        ),
    ]
